### PR TITLE
Clarify users that a create_index field is needed in the Settings.toml file

### PR DESCRIPTION
**Pull request by zenodeapp**
This is a clarification on how to fix the issue explained in #95.

### CODE REVIEW

**Comment by zenodeapp** [comment]
If default should be 'false' tell me!

**Review by rllola — APPROVED** [review]

**Comment by rllola** [comment]
@zenodeapp Can you accept the CLA and I can merge this

**Comment by zenodeapp** [comment]
> @zenodeapp Can you accept the CLA and I can merge this

Done! Was in a phone call, forgive me.

**Comment by rllola** [comment]
No problem @zenodeapp. We are all good now. Merging it.
Thanks for your contribution.

**Pull request merged**
