### PR TITLE
Update views tx_vote_proposal and tx_transfer

### PR DESCRIPTION
**Pull request by opsecx**
The views tx_vote_proposal and tx_transfer took in all transactions regardless of status (failed/succeeded). Updated views to only use successful transactions, as in former version tables. Note: An alternate approach might be to make the views richer and include fail/success status in tables. For now this is a quick fix.

(I assume this may be an issue with the other views as well, but not familiar enough with the data to fix atm. I have validated the data from this particular fix against former databases and seen that it's better corresponding)

### CODE REVIEW

**Comment by opsecx** [comment]
I may have made things difficult by not removing a former commit, not sure if that's problematic for revision history, not sure how to fix that. Lmk if needs changing

**Review by rllola — APPROVED** [review]

**Comment by rllola** [comment]
There is no conflict so we should be good.

**Comment by opsecx** [comment]
I see there's a build failing in checks, but not familiar enough with process to know if significant.

**Comment by rllola** [comment]
Don't worry it is earthly. It is part of our devops process and it is not required.

**Pull request merged**
