### PR TITLE
INSERT has more expressions than target columns (issue #104)

### PR DESCRIPTION
**Pull request by zenodeapp**
Fixes issue #104 where too many VALUES were given to the tx_bridge_pool table.

### CODE REVIEW

**Comment by Pa1amar** [comment]
thanks, this fixed my error.
```  2024-02-08T12:13:03.471824Z ERROR namadexer::indexer: Closing block producer task due to an error saving last block: Database error: error returned from database: INSERT has more expressions than target columns
    at src/indexer/mod.rs:229

  2024-02-08T12:13:03.472075Z  INFO namadexer::indexer: Got block 1834
    at src/indexer/mod.rs:51
    in namadexer::indexer::get_block with block_height: 1834
```

**Comment by SNSMLN** [comment]
same error

```
in namadexer::database::save_block with block_results: Response { height: block::Height(1831), ............
..........
Failed running wasm with: RuntimeError: unreachable\n    at <unnamed> (<module>[622]:0x534ad)\n    at <unnamed> (<module>[76]:0x1b976)\n    at <unnamed
> (<module>[73]:0x1b7ba)\n    at <unnamed> (<module>[11]:0x125e1)\n    at <unnamed> (<module>[649]:0x5473a)", index: true }] }]), validator_updates: [], consensus_param_updates: None, app_hash: AppHash() }                                                                                                                                                                                                                                                           

ERROR namadexer::indexer: Closing block producer task due to an error saving last block: Database error: error returned from database: INSERT has more expressions than target columns
    at src/indexer/mod.rs:229

Error: DB(Database(PgDatabaseError { severity: Error, code: "42601", message: "INSERT has more expressions than target columns", detail: None, hint: None, position: Some(Original(397)), where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("analyze.c"), line: Some(949), routine: Some("transformInsertRow") }))


```

```
git rev-parse HEAD
a324033ab367f6d2bcc66cbb2704aa984d424135
```

```
git tag --contains HEAD
v0.1.0-rc.3
```

**Review by rllola — APPROVED** [review]

**Comment by rllola** [comment]
On which network did you find this ? It doesn't show on the current shielded-expedition

**Comment by Pa1amar** [comment]
> On which network did you find this ? It doesn't show on the current shielded-expedition

I see the same thing on the `shielded-expedition.88f17d1d14`

```
  2024-02-08T18:40:51.705055Z ERROR namadexer::indexer: Closing block producer task due to an error saving last block: Database error: error returned from database: INSERT has more expressions than target columns
    at src/indexer/mod.rs:229

  2024-02-08T18:40:51.705174Z  INFO namadexer::indexer: Got block 1834
    at src/indexer/mod.rs:51
    in namadexer::indexer::get_block with block_height: 1834
```

**Comment by zenodeapp** [comment]
Find it weird that this issue wasn't present in every indexer.

Do you want me to pull and merge the latest?

**Comment by zenodeapp** [comment]
Merged again, so requires approval to test again. (Think the latest commit fixed one of the workflows?)

**Comment by zenodeapp** [comment]
Reporting back, I completely wiped, pulled the latest commit from the repo and did this PR by hand again and the indexer is at the current block height now. So it all should work after this PR gets merged.

On to the next indexer-halt 😅.

**Comment by rllola** [comment]
I have checked and it it was indeed left from an old structure. I am running the tests and this should be good to merge!

> On to the next indexer-halt 😅.

:sweat_smile: thank you for your contribution

**Comment by zenodeapp** [comment]
> I have checked and it it was indeed left from an old structure. I am running the tests and this should be good to merge!
> 
> > On to the next indexer-halt 😅.
> 
> 😅 thank you for your contribution

Haha, you're very welcome! It was just one single line, I wouldn't have known how to tackle bigger bugs since my experience with Rust is so little!

Should thank you for creating/maintaining this @rllola! Hmm, I want ramen now, now that I saw your name 😴🍜.

**Pull request merged**
